"""Initial

Revision ID: 63429f30bcc4
Revises:
Create Date: 2026-03-28 23:24:19.102797

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63429f30bcc4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stop",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "route_stop",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("route_id", sa.String(), nullable=False),
        sa.Column("stop_id", sa.String(), nullable=False),
        sa.Column("order_ix", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stop_id"],
            ["stop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduled_trip",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("route_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduled_stop_time",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dep_time", sa.Time(), nullable=False),
        sa.Column("route_stop_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_trip_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_stop_id"],
            ["route_stop.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_trip_id"],
            ["scheduled_trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "real_stop_times",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("delay_secs", sa.Integer(), nullable=False),
        sa.Column("scheduled_stop_time_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheduled_stop_time_id"],
            ["scheduled_stop_time.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("real_stop_times")
    op.drop_table("scheduled_stop_time")
    op.drop_table("scheduled_trip")
    op.drop_table("route_stop")
    op.drop_index("idx_stop_location", table_name="stop", postgresql_using="gist")
    op.drop_table("stop")
    op.drop_table("route")
    # ### end Alembic commands ###
